# Generated by Django 5.2.17 on 2026-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.IntegerField(choices=[(1, 'Section 1'), (2, 'Section 2')], default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='section1_end',
            field=models.TimeField(default='11:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='section1_start',
            field=models.TimeField(default='07:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='section2_end',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='section2_start',
            field=models.TimeField(default='13:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_days',
            field=models.CharField(default='mon,tue,wed,thu,fri', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('absent', 'Absent')], default='checked_in', max_length=20),
        ),
    ]
