# Generated by Django 5.2.17 on 2026-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_employee_phone_number_employee_reporting_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
