# Generated by Django 5.2.17 on 2026-09-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_leaverequest_notification_overtimerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='early_leave_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_mode',
            field=models.CharField(choices=[('full_section', 'Full Section'), ('early_leave', 'Early Leave')], default='full_section', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='session',
            field=models.IntegerField(choices=[(0, 'Full Day'), (1, 'Section 1 (Morning)'), (2, 'Section 2 (Afternoon)')], default=1),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='day_type',
            field=models.CharField(default='Section 1 (Morning)', max_length=50),
        ),
    ]
