# Generated by Django 5.2.17 on 2026-09-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_profile_url'),
        ('api', '0006_leaverequest_early_leave_time_and_more'),
    ]

    operations = [
    ]
