const Map<String, String> enUS = {
  // ============== AUTH ==============
  'auth_login': 'Login',
  'auth_signup': 'Sign Up',
  'auth_email': 'Email',
  'auth_password': 'Password',
  'auth_forgot_password': 'Forgot Password?',
  'auth_remember_me': 'Remember me',
  'auth_sign_in': 'Sign In',
  'auth_logout': 'Logout',
  'auth_no_account': 'Don\'t have an account?',
  'auth_have_account': 'Already have an account?',
  'auth_welcome_back': 'Welcome back',
  'auth_enter_details': 'Please enter your details.',
  'auth_google_sign_in': 'Sign in with Google',

  // ============== NAVIGATION ==============
  'nav_home': 'Home',
  'nav_schedule': 'Schedule',
  'nav_create': 'Create',
  'nav_myteam': 'MyTeam',
  'nav_request': 'Request',
  'nav_profile': 'Profile',

  // ============== ATTENDANCE ==============
  'attendance_title': 'Attendance',
  'attendance_check_in': 'Check In',
  'attendance_check_out': 'Check Out',
  'attendance_status': 'Status',
  'attendance_present': 'Present',
  'attendance_absent': 'Absent',
  'attendance_early_leave': 'Early Leave',
  'attendance_pending': 'Pending',
  'attendance_date': 'Date',
  'attendance_time': 'Time',
  'attendance_location': 'Location',
  'attendance_history': 'Attendance History',

  // ============== REQUEST ==============
  'request_title': 'Requests',
  'request_leave': 'Leave Request',
  'request_permission': 'Permission Request',
  'request_overtime': 'Overtime Request',
  'request_submit': 'Submit Request',
  'request_pending': 'Pending',
  'request_approved': 'Approved',
  'request_rejected': 'Rejected',
  'request_from_date': 'From Date',
  'request_to_date': 'To Date',
  'request_reason': 'Reason',

  // ============== PROFILE ==============
  'profile_title': 'Profile',
  'profile_name': 'Name',
  'profile_email': 'Email',
  'profile_phone': 'Phone',
  'profile_role': 'Role',
  'profile_department': 'Department',
  'profile_joined': 'Joined',
  'profile_edit': 'Edit Profile',

  // ============== SETTINGS ==============
  'settings_title': 'Settings',
  'settings_appearance': 'Appearance',
  'settings_language': 'Language',
  'settings_theme': 'Theme',
  'settings_theme_system': 'System',
  'settings_theme_light': 'Light',
  'settings_theme_dark': 'Dark',
  'settings_language_english': 'English',
  'settings_language_khmer': 'ខ្មែរ',
  'settings_about': 'About',
  'settings_version': 'Version',

  // ============== COMMON ==============
  'common_yes': 'Yes',
  'common_no': 'No',
  'common_ok': 'OK',
  'common_cancel': 'Cancel',
  'common_save': 'Save',
  'common_delete': 'Delete',
  'common_edit': 'Edit',
  'common_add': 'Add',
  'common_search': 'Search',
  'common_filter': 'Filter',
  'common_loading': 'Loading...',
  'common_error': 'Error',
  'common_success': 'Success',
  'common_warning': 'Warning',
  'common_info': 'Information',
  'common_no_data': 'No data available',
  'common_try_again': 'Try Again',
  'common_close': 'Close',

  // ============== VALIDATION ==============
  'validation_required_field': 'This field is required',
  'validation_invalid_email': 'Please enter a valid email',
  'validation_password_min_length': 'Password must be at least 6 characters',
  'validation_passwords_not_match': 'Passwords do not match',
};
