const Map<String, String> enUS = {
  // ============== AUTH ==============
  'auth_login': 'Login',
  'auth_signup': 'Sign Up',
  'auth_email': 'Email',
  'auth_password': 'Password',
  'auth_forgot_password': 'Forgot Password?',
  'auth_remember_me': 'Remember me',
  'auth_sign_in': 'Sign In',
  'auth_logout': 'Logout',
  'auth_no_account': 'Don\'t have an account?',
  'auth_have_account': 'Already have an account?',
  'auth_welcome_back': 'Welcome back',
  'auth_enter_details': 'Please enter your details.',
  'auth_google_sign_in': 'Sign in with Google',

  // ============== NAVIGATION ==============
  'nav_home': 'Home',
  'nav_schedule': 'Schedule',
  'nav_create': 'Create',
  'nav_myteam': 'MyTeam',
  'nav_request': 'Request',
  'nav_profile': 'Profile',

  // ============== ATTENDANCE & CLOCK ==============
  'attendance_title': 'Attendance',
  'attendance_check_in': 'Check In',
  'attendance_check_out': 'Check Out',
  'attendance_status': 'Status',
  'attendance_present': 'Present',
  'attendance_absent': 'Absent',
  'attendance_early_leave': 'Early Leave',
  'attendance_pending': 'Pending',
  'attendance_date': 'Date',
  'attendance_time': 'Time',
  'attendance_location': 'Location',
  'attendance_history': 'Attendance History',

  // ============== REQUEST ==============
  'request_title': 'Requests',
  'request_leave': 'Leave Request',
  'request_permission': 'Permission Request',
  'request_overtime': 'Overtime Request',
  'request_submit': 'Submit Request',
  'request_pending': 'Pending',
  'request_approved': 'Approved',
  'request_rejected': 'Rejected',
  'request_from_date': 'From Date',
  'request_to_date': 'To Date',
  'request_reason': 'Reason',

  // ============== PROFILE ==============
  'profile_title': 'Profile',
  'profile_name': 'Name',
  'profile_email': 'Email',
  'profile_phone': 'Phone',
  'profile_role': 'Role',
  'profile_department': 'Department',
  'profile_joined': 'Joined',
  'profile_edit': 'Edit Profile',

  // ============== SETTINGS ==============
  'settings_title': 'Settings',
  'settings_appearance': 'Appearance',
  'settings_language': 'Language',
  'settings_theme': 'Theme',
  'settings_theme_system': 'System',
  'settings_theme_light': 'Light',
  'settings_theme_dark': 'Dark',
  'settings_language_english': 'English',
  'settings_language_khmer': 'ខ្មែរ',
  'settings_about': 'About',
  'settings_version': 'Version',

  // ============== COMMON ==============
  'common_yes': 'Yes',
  'common_no': 'No',
  'common_ok': 'OK',
  'common_cancel': 'Cancel',
  'common_save': 'Save',
  'common_delete': 'Delete',
  'common_edit': 'Edit',
  'common_add': 'Add',
  'common_search': 'Search',
  'common_filter': 'Filter',
  'common_loading': 'Loading...',
  'common_error': 'Error',
  'common_success': 'Success',
  'common_warning': 'Warning',
  'common_info': 'Information',
  'common_no_data': 'No data available',
  'common_try_again': 'Try Again',
  'common_close': 'Close',

  // ============== VALIDATION ==============
  'validation_required_field': 'This field is required',
  'validation_invalid_email': 'Please enter a valid email',
  'validation_password_min_length': 'Password must be at least 6 characters',
  'validation_passwords_not_match': 'Passwords do not match',

  // ============== UI LITERAL STRINGS ==============
  'Home': 'Home',
  'Schedule': 'Schedule',
  'MyTeam': 'MyTeam',
  'My Team': 'My Team',
  'Request': 'Request',
  'Requests': 'Requests',
  'Profile': 'Profile',
  'Settings': 'Settings',
  'Face Attendance Settings': 'Face Attendance Settings',
  'Today\'s Attendance': 'Today\'s Attendance',
  'Clock In': 'Clock In',
  'Clock Out': 'Clock Out',
  'CHECK IN': 'CHECK IN',
  'CHECK OUT': 'CHECK OUT',
  'IN': 'IN',
  'OUT': 'OUT',
  'SESSION': 'SESSION',
  'Session': 'Session',
  'Session 1': 'Session 1',
  'Session 2': 'Session 2',
  'MORNING': 'MORNING',
  'AFTERNOON': 'AFTERNOON',
  'Morning': 'Morning',
  'Afternoon': 'Afternoon',
  'Scheduled': 'Scheduled',
  'In Progress': 'In Progress',
  'Completed': 'Completed',
  'Completed for Today': 'Completed for Today',
  'Absent': 'Absent',
  'Open': 'Open',
  'Upcoming': 'Upcoming',
  'Ready': 'Ready',
  'Register Face': 'Register Face',
  'Register Face First': 'Register Face First',
  'Update Registered Face': 'Update Registered Face',
  'Enroll your face first': 'Enroll your face first',
  'Session 1 • Face or Tap ID': 'Session 1 • Face or Tap ID',
  'Session 1 • Tap to check out': 'Session 1 • Tap to check out',
  'Session 2 • Face or Tap ID': 'Session 2 • Face or Tap ID',
  'Session 2 • Tap to finish shift': 'Session 2 • Tap to finish shift',
  'All Sessions Recorded': 'All Sessions Recorded',
  'Request Time Adjustment': 'Request Time Adjustment',
  'Daily Progress': 'Daily Progress',
  'Daily Goal': 'Daily Goal',
  'GOAL': 'GOAL',
  'hrs': 'hrs',
  'hours': 'hours',
  'Wi-Fi: Connected': 'Wi-Fi: Connected',
  'Office Wi-Fi Connected': 'Office Wi-Fi Connected',
  'Office Wi-Fi Not Connected': 'Office Wi-Fi Not Connected',
  'Wi-Fi Verification': 'Wi-Fi Verification',
  'Have a productive day': 'Have a productive day',
  'Good Morning': 'Good Morning',
  'Good Afternoon': 'Good Afternoon',
  'Good Evening': 'Good Evening',
  'Early Check-Out Alert': 'Early Check-Out Alert',
  'Request Leave': 'Request Leave',
  'Check Out Now': 'Check Out Now',
  'Cancel': 'Cancel',
  'CEO Management': 'CEO Management',
  'Quick administrative actions': 'Quick administrative actions',
  'CLOCK ATTENDANCE': 'CLOCK ATTENDANCE',
  'Full View': 'Full View',
  'CEO': 'CEO',
  'Manager': 'Manager',
  'Leader': 'Leader',
  'Employee': 'Employee',
  'HR': 'HR',
  'Working Days': 'Working Days',
  'Working Hours': 'Working Hours',
  'Attendance Rate': 'Attendance Rate',
  'Overtime Hours': 'Overtime Hours',
  'Monthly Summary': 'Monthly Summary',
  'Performance': 'Performance',
  'Work Schedule': 'Work Schedule',
  'Worked': 'Worked',
  'Workday': 'Workday',
  'Day off': 'Day off',
  'Leave': 'Leave',
  'Overtime': 'Overtime',
  'No record': 'No record',
  'Days Present': 'Days Present',
  'Days Absent': 'Days Absent',
  'Leave Days': 'Leave Days',
  'You\'re on track': 'You\'re on track',
  'Mon': 'Mon',
  'Tue': 'Tue',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Fri',
  'Sat': 'Sat',
  'Sun': 'Sun',
  'Search team members...': 'Search team members...',
  'All': 'All',
  'Present': 'Present',
  'On Leave': 'On Leave',
  'Active': 'Active',
  'Team Attendance': 'Team Attendance',
  'Total Members': 'Total Members',
  'Call': 'Call',
  'Message': 'Message',
  'Adjust Session Time': 'Adjust Session Time',
  'Change Session Time': 'Change Session Time',
  'No members found': 'No members found',
  'Team Members': 'Team Members',
  'Shift Details': 'Shift Details',
  'Save Changes': 'Save Changes',
  'PENDING APPROVALS': 'PENDING APPROVALS',
  'Pending': 'Pending',
  'Approved': 'Approved',
  'Rejected': 'Rejected',
  'MANAGEMENT & SERVICES': 'MANAGEMENT & SERVICES',
  'My Schedule': 'My Schedule',
  'Leave Request': 'Leave Request',
  'Edit Leave Request': 'Edit Leave Request',
  'Overtime Request': 'Overtime Request',
  'Edit Overtime Request': 'Edit Overtime Request',
  'Suggestion Box': 'Suggestion Box',
  'Submit Feedback': 'Submit Feedback',
  'Feedback': 'Feedback',
  'History & Status': 'History & Status',
  'History & Pending': 'History & Pending',
  'Permission & Authorization': 'Permission & Authorization',
  'Permission': 'Permission',
  'Request Permission': 'Request Permission',
  'Request Information': 'Request Information',
  'Request Detail': 'Request Detail',
  'Submit Request': 'Submit Request',
  'Submit': 'Submit',
  'Reason': 'Reason',
  'Reason / Note': 'Reason / Note',
  'Enter your reason here...': 'Enter your reason here...',
  'Write your suggestion first.': 'Write your suggestion first.',
  'Your suggestion was submitted.': 'Your suggestion was submitted.',
  'From Date': 'From Date',
  'To Date': 'To Date',
  'Date': 'Date',
  'Time': 'Time',
  'Start Time': 'Start Time',
  'End Time': 'End Time',
  'Duration': 'Duration',
  'Full Day': 'Full Day',
  'Half Day': 'Half Day',
  'Section 1': 'Section 1',
  'Section 2': 'Section 2',
  'Section 1 (Morning)': 'Section 1 (Morning)',
  'Section 2 (Afternoon)': 'Section 2 (Afternoon)',
  'Early Leave': 'Early Leave',
  'Early Departure': 'Early Departure',
  'Attachment': 'Attachment',
  'Choose File': 'Choose File',
  'Change': 'Change',
  'Remove': 'Remove',
  'Approve': 'Approve',
  'Reject': 'Reject',
  'Export PDF': 'Export PDF',
  'Export Report': 'Export Report',
  'Download Report': 'Download Report',
  'This Month': 'This Month',
  'Last Month': 'Last Month',
  'Custom Range': 'Custom Range',
  'Select Date Range': 'Select Date Range',
  'Select Date': 'Select Date',
  'No requests pending your review.': 'No requests pending your review.',
  'No requests found': 'No requests found',
  'ATTENDANCE CALENDAR': 'ATTENDANCE CALENDAR',
  'FACE BIOMETRICS': 'FACE BIOMETRICS',
  'PREFERENCES': 'PREFERENCES',
  'ACCOUNT': 'ACCOUNT',
  'ROLE-BASED PANEL ACCESS': 'ROLE-BASED PANEL ACCESS',
  'All Authorized': 'All Authorized',
  'CEO Control Panel': 'CEO Control Panel',
  'Full system oversight and executive controls': 'Full system oversight and executive controls',
  'Manager Portal': 'Manager Portal',
  'Team management & approval workflows': 'Team management & approval workflows',
  'Leader View': 'Leader View',
  'Direct team oversight & task delegation': 'Direct team oversight & task delegation',
  'Employee Workspace': 'Employee Workspace',
  'Personal dashboard & self-service tools': 'Personal dashboard & self-service tools',
  'Face biometrics enrolled • Tap to re-scan': 'Face biometrics enrolled • Tap to re-scan',
  'Face biometrics required • Tap to enroll now': 'Face biometrics required • Tap to enroll now',
  'Settings & Language': 'Settings & Language',
  'English (US) • Notifications': 'English (US) • Notifications',
  'Khmer • Notifications': 'Khmer • Notifications',
  'Log Out': 'Log Out',
  'Are you sure you want to log out of your account?': 'Are you sure you want to log out of your account?',
  'Updating profile picture...': 'Updating profile picture...',
  'Profile picture updated successfully!': 'Profile picture updated successfully!',
  'LANGUAGE / ភាសា': 'LANGUAGE / ភាសា',
  'LANGUAGE': 'LANGUAGE',
  'Language': 'Language',
  'App content and interface language': 'App content and interface language',
  'ABOUT': 'ABOUT',
  'About': 'About',
  'Terms of Service': 'Terms of Service',
  'Privacy Policy': 'Privacy Policy',
  'Support & Documentation': 'Support & Documentation',
  'Latest': 'Latest',
  'Notifications': 'Notifications',
  'Mark all as read': 'Mark all as read',
  'Clear all': 'Clear all',
  'No notifications': 'No notifications',
  'No notifications yet': 'No notifications yet',
  'Executive Actions': 'Executive Actions',
  'System configuration and resource creation': 'System configuration and resource creation',
  'Biometric Security & Anti-Spoofing': 'Biometric Security & Anti-Spoofing',
  'kby-ai on-device matching engine': 'kby-ai on-device matching engine',
  'Organization Overview': 'Organization Overview',
  'Total Employees': 'Total Employees',
  'Today Attendance': 'Today Attendance',
  'Create Employee': 'Create Employee',
  'Create Branch': 'Create Branch',
  'Create Department': 'Create Department',
  'Employee List': 'Employee List',
  'Branches': 'Branches',
  'Departments': 'Departments',
  'Refresh Telemetry': 'Refresh Telemetry',
  'Face Attendance Security Suite': 'Face Attendance Security Suite',
  'All rights reserved.': 'All rights reserved.',
  'English': 'English',
  'Khmer': 'Khmer',
  'Success': 'Success',
  'Error': 'Error',
  'Warning': 'Warning',
  'OK': 'OK',
  'Yes': 'Yes',
  'No': 'No',
  'Save': 'Save',
  'Delete': 'Delete',
  'Edit': 'Edit',
  'Close': 'Close',
  'Loading...': 'Loading...',
  'Try Again': 'Try Again',
  'No data available': 'No data available',

  // Additional screen literals
  'TOTAL HOURS WORKED': 'TOTAL HOURS WORKED',
  'Goal Reached!': 'Goal Reached!',
  'Done!': 'Done!',
  'remaining': 'remaining',
  'of 8.0h goal': 'of 8.0h goal',
  'Office Wi-Fi Connected • Main HQ': 'Office Wi-Fi Connected • Main HQ',
  'Executive Attendance': 'Executive Attendance',
  'All Shifts Recorded': 'All Shifts Recorded',
  'Clocked In • Shift in progress': 'Clocked In • Shift in progress',
  'Ready to Clock In': 'Ready to Clock In',
  'TODAY\'S SHIFT': 'TODAY\'S SHIFT',
  'WORKED': 'WORKED',
  'Full telemetry, biometric controls & organization oversight': 'Full telemetry, biometric controls & organization oversight',
  'Set up branch location & GPS geofence': 'Set up branch location & GPS geofence',
  'Add department to an existing branch': 'Add department to an existing branch',
  'Create User': 'Create User',
  'Invite Manager, Leader, or Employee': 'Invite Manager, Leader, or Employee',
  'Created Branches': 'Created Branches',
  'Created Departments': 'Created Departments',
  'Invited Users': 'Invited Users',
  'View All': 'View All',
  'Radius': 'Radius',
  'geofence': 'geofence',
  'staff': 'staff',
  'Branch': 'Branch',
  'Employees': 'Employees',
  'Face ID Registered': 'Face ID Registered',
  'Face ID Not Registered': 'Face ID Not Registered',
  'Sign out of your session on this device': 'Sign out of your session on this device',
  'Calendar View': 'Calendar View',
  'Absence Permission Info': 'Absence Permission Info',
  'Permitted': 'Permitted',
  'Leave Type': 'Leave Type',
  'Approved By': 'Approved By',
  'Time Range': 'Time Range',
  'Documentation': 'Documentation',
  'This absence has verified management permission and does not reduce attendance rating.': 'This absence has verified management permission and does not reduce attendance rating.',
  'Got It': 'Got It',
  'Tap to view leave details': 'Tap to view leave details',
  'Tap to view permission reason': 'Tap to view permission reason',
  'days worked': 'days worked',
  'complete': 'complete',
  'days to go': 'days to go',
  'Days Goal': 'Days Goal',
  'On-Time Rate': 'On-Time Rate',
  'Limit': 'Limit',
  'Holiday': 'Holiday',
  'No Shifts Scheduled': 'No Shifts Scheduled',
  'No scheduled shifts found for this period.': 'No scheduled shifts found for this period.',
  'Nothing here yet': 'Nothing here yet',
  'Public holidays will appear here once they are added.': 'Public holidays will appear here once they are added.',
  'Your leave days will appear here once they are approved.': 'Your leave days will appear here once they are approved.',
  'h': 'h',
  'Pinned': 'Pinned',
  'Search by name, role, or branch': 'Search by name, role, or branch',
  'No team members found': 'No team members found',
  'Try searching by a different name, role, or branch.': 'Try searching by a different name, role, or branch.',
  'Failed to load team data': 'Failed to load team data',
  'Retry': 'Retry',
  'Unpin': 'Unpin',
  'Pin': 'Pin',
  'No phone number available': 'No phone number available',
  'Apply': 'Apply',
  'REQUEST ACTIVITY': 'REQUEST ACTIVITY',
  'History': 'History',
  'Unauthorized': 'Unauthorized',
  'Pending review': 'Pending review',
  'Authorized': 'Authorized',
  'Completed & archived': 'Completed & archived',
  'Total': 'Total',
  'Session 1 • Morning': 'Session 1 • Morning',
  'Session 2 • Afternoon': 'Session 2 • Afternoon',
  'All Sessions Done': 'All Sessions Done',
  'Done': 'Done',
  'Setup': 'Setup',
  'January': 'January',
  'February': 'February',
  'March': 'March',
  'April': 'April',
  'May': 'May',
  'June': 'June',
  'July': 'July',
  'August': 'August',
  'September': 'September',
  'October': 'October',
  'November': 'November',
  'December': 'December',
  'Monday': 'Monday',
  'Tuesday': 'Tuesday',
  'Wednesday': 'Wednesday',
  'Thursday': 'Thursday',
  'Friday': 'Friday',
  'Saturday': 'Saturday',
  'Sunday': 'Sunday',

  // Session Time Dialog & My Team
  'Total Daily Scheduled Work:': 'Total Daily Scheduled Work:',
  'Session 1 (Morning Shift)': 'Session 1 (Morning Shift)',
  'Session 2 (Afternoon Shift)': 'Session 2 (Afternoon Shift)',
  'ACTIVE WORK DAYS': 'ACTIVE WORK DAYS',
  'Mon-Fri': 'Mon-Fri',
  'Save Session Schedule': 'Save Session Schedule',
  'Start (Check-in)': 'Start (Check-in)',
  'End (Check-out)': 'End (Check-out)',
  'Session 1: End time must be after start time.': 'Session 1: End time must be after start time.',
  'Session 2: Cannot start before Session 1 ends.': 'Session 2: Cannot start before Session 1 ends.',
  'Session 2: End time must be after start time.': 'Session 2: End time must be after start time.',
  'Please select at least one active work day.': 'Please select at least one active work day.',
  'Session Updated': 'Session Updated',
  'Work schedule was successfully updated.': 'Work schedule was successfully updated.',
  'SESSION 1': 'SESSION 1',
  'SESSION 2': 'SESSION 2',
  'Request permissions or authorization changes': 'Request permissions or authorization changes',
  'Permission Request': 'Permission Request',
  'Days Worked': 'Days Worked',
  'Early leave at': 'Early leave at',
  'Full Day Leave': 'Full Day Leave',
  'on': 'on',
  'CEO Hub': 'CEO Hub',
  'Manager Hub': 'Manager Hub',
  'Leader Hub': 'Leader Hub',
  'Executive Administration & Shifts': 'Executive Administration & Shifts',
  'Organization & Team Actions': 'Organization & Team Actions',
  'Team Growth & Invites': 'Team Growth & Invites',
  'Manage organizational departments, change user session times, and coordinate staff.': 'Manage organizational departments, change user session times, and coordinate staff.',
  'Create departments and invite Leaders or Employees to your organization.': 'Create departments and invite Leaders or Employees to your organization.',
  'Invite new Employees to join your operational team.': 'Invite new Employees to join your operational team.',
  'QUICK ACTIONS': 'QUICK ACTIONS',
  'DIRECTORIES': 'DIRECTORIES',
  'Invite Staff / Manager': 'Invite Staff / Manager',
  'Invite User': 'Invite User',
  'Invite Employee': 'Invite Employee',
  'Invite a Manager, Leader, or Employee': 'Invite a Manager, Leader, or Employee',
  'Invite a Leader or Employee to join': 'Invite a Leader or Employee to join',
  'Invite a new Employee to your team': 'Invite a new Employee to your team',
  'Departments List': 'Departments List',
  'View and manage created departments': 'View and manage created departments',
  'Staff & Session Schedules': 'Staff & Session Schedules',
  'Staff & Users Directory': 'Staff & Users Directory',
  'Team Directory': 'Team Directory',
  'View staff profiles, change session times, and manage users': 'View staff profiles, change session times, and manage users',
  'View staff, resend invitations, and manage members': 'View staff, resend invitations, and manage members',
  'Both Shifts': 'Both Shifts',
  'Leave Option for': 'Leave Option for',
  'Full': 'Full',
  'Leave Early': 'Leave Early',
  'Departure Time': 'Departure Time',
  'Target Workday': 'Target Workday',
  'Today • Workday': 'Today • Workday',
  'Selected Date': 'Selected Date',
  'Work Section to Leave': 'Work Section to Leave',
  'Full Day Leave excuses both morning (Section 1) and afternoon (Section 2) shifts.': 'Full Day Leave excuses both morning (Section 1) and afternoon (Section 2) shifts.',
  'Max 250 characters': 'Max 250 characters',
  'Please provide details about your leave request...': 'Please provide details about your leave request...',
  'Attach Document or Image (PDF, JPG, PNG)': 'Attach Document or Image (PDF, JPG, PNG)',
  'Update Leave Request': 'Update Leave Request',
  'Submit Leave Request': 'Submit Leave Request',
  'Submitting...': 'Submitting...',
  'Requests require approval from your direct manager': 'Requests require approval from your direct manager',
  'No Leave Requests Yet': 'No Leave Requests Yet',
  'Your submitted leave requests will appear here with live review status.': 'Your submitted leave requests will appear here with live review status.',
  'Review note:': 'Review note:',
  'View Details': 'View Details',
  'Cancel Request': 'Cancel Request',
  'Are you sure you want to cancel this leave request?': 'Are you sure you want to cancel this leave request?',
  'Keep': 'Keep',
  'Yes, Cancel': 'Yes, Cancel',
  'Full Day (Both Sections)': 'Full Day (Both Sections)',
  'Total Days': 'Total Days',
  'Leave Time': 'Leave Time',
  'Supporting Document': 'Supporting Document',
  'Reviewed By': 'Reviewed By',
  'Review Notes': 'Review Notes',
  'MONTH ALLOWANCE': 'MONTH ALLOWANCE',
  'Used': 'Used',
  'Quota Filled': 'Quota Filled',
  'hrs remaining': 'hrs remaining',
  'SHIFT INTERVAL': 'SHIFT INTERVAL',
  'DURATION': 'DURATION',
  'Total Overtime': 'Total Overtime',
  'Submit Overtime Request': 'Submit Overtime Request',
  'Update Overtime Request': 'Update Overtime Request',
  'No Overtime Requests Yet': 'No Overtime Requests Yet',
  'Your submitted overtime requests will appear here with review status.': 'Your submitted overtime requests will appear here with review status.',
  'Overtime Guidelines': 'Overtime Guidelines',
  'Understood': 'Understood',
  'Download PDF Report': 'Download PDF Report',
  'Help': 'Help',
  'Anything we can do better?': 'Anything we can do better?',
  'Even the smallest suggestion can help us improve together': 'Even the smallest suggestion can help us improve together',
  'CATEGORY': 'CATEGORY',
  'Workplace & Equipment': 'Workplace & Equipment',
  'Shift Schedule': 'Shift Schedule',
  'Team Culture': 'Team Culture',
  'Other': 'Other',
  'YOUR SUGGESTION': 'YOUR SUGGESTION',
  'Share your thoughts, suggestions, or concerns...': 'Share your thoughts, suggestions, or concerns...',
  'Constructive feedback is shared directly with ops': 'Constructive feedback is shared directly with ops',
  'Submit anonymously': 'Submit anonymously',
  'Your identity will not be attached': 'Your identity will not be attached',
  'No suggestions yet': 'No suggestions yet',
  'Delete suggestion?': 'Delete suggestion?',
  'This cannot be undone.': 'This cannot be undone.',
  'Your Message': 'Your Message',
  'Mark as seen?': 'Mark as seen?',
  'Mark as seen': 'Mark as seen',
  'The employee will no longer be able to edit this suggestion.': 'The employee will no longer be able to edit this suggestion.',
  'Pending Request': 'Pending Request',
  'Completed Request': 'Completed Request',
  'Pick Date': 'Pick Date',
  'Back to session list': 'Back to session list',
  'Add another session': 'Add another session',
  'Request List': 'Request List',
  'No added request': 'No added request',
  'No pending requests': 'No pending requests',
  'No approved requests': 'No approved requests',
  'Save changes': 'Save changes',
  'Keep request': 'Keep request',
  'Yes, cancel': 'Yes, cancel',
  'Change this approved request?': 'Change this approved request?',
  'After you save, the request goes back to Pending and needs approval again.': 'After you save, the request goes back to Pending and needs approval again.',
  'Keep as approved': 'Keep as approved',
  'Yes, change it': 'Yes, change it',
  'This date has already passed, so the request can no longer be changed.': 'This date has already passed, so the request can no longer be changed.',
  'Mark all read': 'Mark all read',
  'You will be notified about request updates and approvals here.': 'You will be notified about request updates and approvals here.',
  'Align your face within the frame': 'Align your face within the frame',
  'GPS Ready': 'GPS Ready',
  'Locating...': 'Locating...',
  'Retry Camera Connection': 'Retry Camera Connection',
  'Success!': 'Success!',
  'Biometric Match:': 'Biometric Match:',
  'Liveness Score:': 'Liveness Score:',
  'Security Alert: Biometric Mismatch': 'Security Alert: Biometric Mismatch',
  'Face Verification Failed': 'Face Verification Failed',
  'Outside Check-In Window': 'Outside Check-In Window',
  'Location Out of Range': 'Location Out of Range',
  'Total Duration:': 'Total Duration:',
  'REASON FOR OVERTIME': 'REASON FOR OVERTIME',
  'Please write your detailed reason here...': 'Please write your detailed reason here...',
  'Attach Work Log or Task Screenshot (PDF, JPG, PNG)': 'Attach Work Log or Task Screenshot (PDF, JPG, PNG)',
  'Requests are subject to manager approval within 24 hours.': 'Requests are subject to manager approval within 24 hours.',
  'Monthly Attendance Report': 'Monthly Attendance Report',
  'Export overtime summary as PDF': 'Export overtime summary as PDF',
  'Export': 'Export',
  'No Overtime Requests': 'No Overtime Requests',
  'Submitted overtime logs and approval updates will appear here.': 'Submitted overtime logs and approval updates will appear here.',
  'From Time': 'From Time',
  'To Time': 'To Time',
  'h of 20h Used': 'h of 20h Used',
  'overtime_guidelines_body':
      '• Standard monthly overtime quota is 20 hours per employee.\n• Overtime requests must specify clear business justification and tasks worked.\n• Requests are reviewed and approved by your direct supervisor within 24 hours.\n• Monthly reports can be downloaded in PDF format from the History tab.',
  'This request could not be found.': 'This request could not be found.',
  '0 minutes': '0 minutes',
  'minute': 'minute',
  'minutes': 'minutes',
  '0 HOURS': '0 HOURS',
  'HOUR': 'HOUR',
  'HOURS': 'HOURS',
  'KB • Tap Change to replace': 'KB • Tap Change to replace',
  'Enter the reason for the overtime.': 'Enter the reason for the overtime.',
  'To time must be after from time.': 'To time must be after from time.',
  'Your overtime request was updated.': 'Your overtime request was updated.',
  'This request was already approved, so it cannot be edited.': 'This request was already approved, so it cannot be edited.',
  'Overtime request submitted.': 'Overtime request submitted.',
  'Attachment removed.': 'Attachment removed.',
  'Could not create the PDF. Please try again.': 'Could not create the PDF. Please try again.',
  'From:': 'From:',
  'Just now': 'Just now',
  'm ago': 'm ago',
  'h ago': 'h ago',
  'd ago': 'd ago',
  'Upload Photo Instead': 'Upload Photo Instead',
  'Camera loading or permission required': 'Camera loading or permission required',
  'Please ensure your camera is connected and permitted to enroll your face biometric.': 'Please ensure your camera is connected and permitted to enroll your face biometric.',
  'You can capture using your webcam or upload a clear photo of your face directly from your computer.': 'You can capture using your webcam or upload a clear photo of your face directly from your computer.',
  'Upload Photo for': 'Upload Photo for',
  'Check In': 'Check In',
  'Check Out': 'Check Out',
  'Face Attendance': 'Face Attendance',
  'Scanning and processing face...': 'Scanning and processing face...',
  'Extracting biometric face features on-device...': 'Extracting biometric face features on-device...',
  'Matching face biometrics & geofence on-device...': 'Matching face biometrics & geofence on-device...',
  'Matching face biometrics for check-out on-device...': 'Matching face biometrics for check-out on-device...',
  'Waiting for GPS fix. Please ensure location is enabled.': 'Waiting for GPS fix. Please ensure location is enabled.',
  'Location Required': 'Location Required',
  'Operation completed successfully.': 'Operation completed successfully.',
  'Your suggestion was updated.': 'Your suggestion was updated.',
  'This suggestion was already seen, so it cannot be edited.': 'This suggestion was already seen, so it cannot be edited.',
  'Suggestion deleted.': 'Suggestion deleted.',
  'This suggestion was already seen, so it cannot be deleted.': 'This suggestion was already seen, so it cannot be deleted.',
  'Suggestion marked as seen.': 'Suggestion marked as seen.',
  'Pick a date first.': 'Pick a date first.',
  'Enter the reason for your request.': 'Enter the reason for your request.',
  'You already have a request for that date and schedule.': 'You already have a request for that date and schedule.',
  'Add at least one session before submitting.': 'Add at least one session before submitting.',
  'Your permission request was submitted.': 'Your permission request was submitted.',
  'Saved. The request is Pending again and needs approval.': 'Saved. The request is Pending again and needs approval.',
  'Your changes were saved.': 'Your changes were saved.',
  'Your request was cancelled.': 'Your request was cancelled.',
  'Branch Management': 'Branch Management',
  'Add New Branch': 'Add New Branch',
  'No branches found': 'No branches found',
  'Create a branch to configure geofence attendance.': 'Create a branch to configure geofence attendance.',
  'Department Management': 'Department Management',
  'Add New Department': 'Add New Department',
  'No departments found': 'No departments found',
  'Create a department to group your staff members.': 'Create a department to group your staff members.',
  'Employee Directory': 'Employee Directory',
  'Add New Employee': 'Add New Employee',
  'No employees found': 'No employees found',
  'Pending Approvals': 'Pending Approvals',
  'Branch Locations & Geofences': 'Branch Locations & Geofences',
  'Departments & Structure': 'Departments & Structure',
  'day': 'day',
  'days': 'days',
  'Invite New Employee': 'Invite New Employee',
  'Add departments to organize teams within branches.': 'Add departments to organize teams within branches.',
  'Attendance': 'Attendance',
  'Overview': 'Overview',
  'Department': 'Department',
  'Month': 'Month',
  'Year': 'Year',
  'All months': 'All months',
  'All years': 'All years',
  'Total Sessions': 'Total Sessions',
  'Absent with Permission': 'Absent with Permission',
  'Waive': 'Waive',
  ' Session': ' Session',
  ' Sessions': ' Sessions',
  'Forgot password?': 'Forgot password?',
  'Enter your email and we\'ll send you a link to reset your password.': 'Enter your email and we\'ll send you a link to reset your password.',
  'Send reset link': 'Send reset link',
  'Back to login': 'Back to login',
  'FAST DEMO ACCESS': 'FAST DEMO ACCESS',
  'Role': 'Role',
  'Pass': 'Pass',
  'Admin': 'Admin',
};
