const Map<String, String> kmKH = {
  // ============== AUTH ==============
  'auth_login': 'ចូលគណនី',
  'auth_signup': 'បង្កើតគណនី',
  'auth_email': 'អ៊ីមែល',
  'auth_password': 'ពាក្យសម្ងាត់',
  'auth_forgot_password': 'ភ្លេចពាក្យសម្ងាត់?',
  'auth_remember_me': 'ចងចាំខ្ញុំ',
  'auth_sign_in': 'ចូលប្រើប្រាស់',
  'auth_logout': 'ចាកចេញ',
  'auth_no_account': 'មិនទាន់មានគណនី?',
  'auth_have_account': 'មានគណនីរួចហើយ?',
  'auth_welcome_back': 'សូមស្វាគមន៍មកកាន់ប្រព័ន្ធ',
  'auth_enter_details': 'សូមបញ្ចូលព័ត៌មានលម្អិតរបស់អ្នក',
  'auth_google_sign_in': 'ចូលគណនីតាមរយៈ Google',

  // ============== NAVIGATION ==============
  'nav_home': 'ទំព័រដើម',
  'nav_schedule': 'កាលវិភាគ',
  'nav_myteam': 'ក្រុមខ្ញុំ',
  'nav_request': 'សំណើ',
  'nav_profile': 'គណនី',

  // ============== ATTENDANCE ==============
  'attendance_title': 'វត្តមាន',
  'attendance_check_in': 'កត់ត្រាចូល',
  'attendance_check_out': 'កត់ត្រាចេញ',
  'attendance_status': 'ស្ថានភាព',
  'attendance_present': 'វត្តមាន',
  'attendance_absent': 'អវត្តមាន',
  'attendance_early_leave': 'ចេញមុនម៉ោង',
  'attendance_pending': 'កំពុងរង់ចាំ',
  'attendance_date': 'កាលបរិច្ឆេទ',
  'attendance_time': 'ពេលវេលា',
  'attendance_location': 'ទីតាំង',
  'attendance_history': 'ប្រវត្តិវត្តមាន',

  // ============== REQUEST ==============
  'request_title': 'សំណើ',
  'request_leave': 'សំណើច្បាប់ឈប់សម្រាក',
  'request_permission': 'សំណើអនុញ្ញាត',
  'request_overtime': 'សំណើធ្វើការបន្ថែមម៉ោង',
  'request_submit': 'ដាក់ស្នើសុំ',
  'request_pending': 'រង់ចាំការអនុម័ត',
  'request_approved': 'បានអនុម័ត',
  'request_rejected': 'បានបដិសេធ',
  'request_from_date': 'ចាប់ពីថ្ងៃ',
  'request_to_date': 'ដល់ថ្ងៃ',
  'request_reason': 'មូលហេតុ',

  // ============== PROFILE ==============
  'profile_title': 'គណនីផ្ទាល់ខ្លួន',
  'profile_name': 'ឈ្មោះ',
  'profile_email': 'អ៊ីមែល',
  'profile_phone': 'លេខទូរស័ព្ទ',
  'profile_role': 'តួនាទី',
  'profile_department': 'ផ្នែក / នាយកដ្ឋាន',
  'profile_joined': 'កាលបរិច្ឆេទចូលបម្រើការងារ',
  'profile_edit': 'កែប្រែព័ត៌មាន',

  // ============== SETTINGS ==============
  'settings_title': 'ការកំណត់',
  'settings_appearance': 'រូបរាង និងពណ៌',
  'settings_language': 'ភាសា',
  'settings_theme': 'រចនាប័ទ្ម',
  'settings_theme_system': 'តាមប្រព័ន្ធ (System)',
  'settings_theme_light': 'ពន្លឺ (Light)',
  'settings_theme_dark': 'ងងឹត (Dark)',
  'settings_language_english': 'English',
  'settings_language_khmer': 'ភាសាខ្មែរ',
  'settings_about': 'អំពីកម្មវិធី',
  'settings_version': 'កំណែកម្មវិធី',

  // ============== COMMON ==============
  'common_yes': 'បាទ / ចាស',
  'common_no': 'ទេ',
  'common_ok': 'យល់ព្រម',
  'common_cancel': 'បោះបង់',
  'common_save': 'រក្សាទុក',
  'common_delete': 'លុប',
  'common_edit': 'កែប្រែ',
  'common_add': 'បន្ថែម',
  'common_search': 'ស្វែងរក',
  'common_filter': 'ចម្រាញ់',
  'common_loading': 'កំពុងផ្ទុក...',
  'common_error': 'មានបញ្ហា',
  'common_success': 'ជោគជ័យ',
  'common_warning': 'ការព្រមាន',
  'common_info': 'ព័ត៌មាន',
  'common_no_data': 'មិនមានទិន្នន័យ',
  'common_try_again': 'ព្យាយាមម្តងទៀត',
  'common_close': 'បិទ',

  // ============== VALIDATION ==============
  'validation_required_field': 'សូមបំពេញព័ត៌មានត្រង់នេះ',
  'validation_invalid_email': 'សូមបញ្ចូលអ៊ីមែលឱ្យបានត្រឹមត្រូវ',
  'validation_password_min_length': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៦ តួអក្សរ',
  'validation_passwords_not_match': 'ពាក្យសម្ងាត់ទាំងពីរមិនត្រូវគ្នាទេ',
};
