const Map<String, String> kmKH = {
  // ============== AUTH ==============
  'auth_login': 'ចូលគណនី',
  'auth_signup': 'បង្កើតគណនី',
  'auth_email': 'អ៊ីមែល',
  'auth_password': 'ពាក្យសម្ងាត់',
  'auth_forgot_password': 'ភ្លេចពាក្យសម្ងាត់?',
  'auth_remember_me': 'ចងចាំខ្ញុំ',
  'auth_sign_in': 'ចូលប្រើប្រាស់',
  'auth_logout': 'ចាកចេញ',
  'auth_no_account': 'មិនទាន់មានគណនី?',
  'auth_have_account': 'មានគណនីរួចហើយ?',
  'auth_welcome_back': 'សូមស្វាគមន៍មកកាន់ប្រព័ន្ធ',
  'auth_enter_details': 'សូមបញ្ចូលព័ត៌មានលម្អិតរបស់អ្នក',
  'auth_google_sign_in': 'ចូលគណនីតាមរយៈ Google',

  // ============== NAVIGATION ==============
  'nav_home': 'ទំព័រដើម',
  'nav_schedule': 'កាលវិភាគ',
  'nav_create': 'បង្កើត',
  'nav_myteam': 'ក្រុមការងារ',
  'nav_request': 'សំណើ',
  'nav_profile': 'គណនី',

  // ============== ATTENDANCE & CLOCK ==============
  'attendance_title': 'វត្តមាន',
  'attendance_check_in': 'កត់ត្រាចូល',
  'attendance_check_out': 'កត់ត្រាចេញ',
  'attendance_status': 'ស្ថានភាព',
  'attendance_present': 'វត្តមាន',
  'attendance_absent': 'អវត្តមាន',
  'attendance_early_leave': 'ចេញមុនម៉ោង',
  'attendance_pending': 'កំពុងរង់ចាំ',
  'attendance_date': 'កាលបរិច្ឆេទ',
  'attendance_time': 'ពេលវេលា',
  'attendance_location': 'ទីតាំង',
  'attendance_history': 'ប្រវត្តិវត្តមាន',

  // ============== REQUEST ==============
  'request_title': 'សំណើ',
  'request_leave': 'សំណើច្បាប់ឈប់សម្រាក',
  'request_permission': 'សំណើអនុញ្ញាត',
  'request_overtime': 'សំណើធ្វើការបន្ថែមម៉ោង',
  'request_submit': 'ដាក់ស្នើសុំ',
  'request_pending': 'រង់ចាំការអនុម័ត',
  'request_approved': 'បានអនុម័ត',
  'request_rejected': 'បានបដិសេធ',
  'request_from_date': 'ចាប់ពីថ្ងៃ',
  'request_to_date': 'ដល់ថ្ងៃ',
  'request_reason': 'មូលហេតុ',

  // ============== PROFILE ==============
  'profile_title': 'គណនីផ្ទាល់ខ្លួន',
  'profile_name': 'ឈ្មោះ',
  'profile_email': 'អ៊ីមែល',
  'profile_phone': 'លេខទូរស័ព្ទ',
  'profile_role': 'តួនាទី',
  'profile_department': 'ផ្នែក / នាយកដ្ឋាន',
  'profile_joined': 'កាលបរិច្ឆេទចូលបម្រើការងារ',
  'profile_edit': 'កែប្រែព័ត៌មាន',

  // ============== SETTINGS ==============
  'settings_title': 'ការកំណត់',
  'settings_appearance': 'រូបរាង និងពណ៌',
  'settings_language': 'ភាសា',
  'settings_theme': 'រចនាប័ទ្ម',
  'settings_theme_system': 'តាមប្រព័ន្ធ (System)',
  'settings_theme_light': 'ពន្លឺ (Light)',
  'settings_theme_dark': 'ងងឹត (Dark)',
  'settings_language_english': 'English',
  'settings_language_khmer': 'ភាសាខ្មែរ',
  'settings_about': 'អំពីកម្មវិធី',
  'settings_version': 'កំណែកម្មវិធី',

  // ============== COMMON ==============
  'common_yes': 'បាទ / ចាស',
  'common_no': 'ទេ',
  'common_ok': 'យល់ព្រម',
  'common_cancel': 'បោះបង់',
  'common_save': 'រក្សាទុក',
  'common_delete': 'លុប',
  'common_edit': 'កែប្រែ',
  'common_add': 'បន្ថែម',
  'common_search': 'ស្វែងរក',
  'common_filter': 'ចម្រាញ់',
  'common_loading': 'កំពុងផ្ទុក...',
  'common_error': 'មានបញ្ហា',
  'common_success': 'ជោគជ័យ',
  'common_warning': 'ការព្រមាន',
  'common_info': 'ព័ត៌មាន',
  'common_no_data': 'មិនមានទិន្នន័យ',
  'common_try_again': 'ព្យាយាមម្តងទៀត',
  'common_close': 'បិទ',

  // ============== VALIDATION ==============
  'validation_required_field': 'សូមបំពេញព័ត៌មានត្រង់នេះ',
  'validation_invalid_email': 'សូមបញ្ចូលអ៊ីមែលឱ្យបានត្រឹមត្រូវ',
  'validation_password_min_length': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៦ តួអក្សរ',
  'validation_passwords_not_match': 'ពាក្យសម្ងាត់ទាំងពីរមិនត្រូវគ្នាទេ',

  // ============== UI LITERAL STRINGS TRANSLATIONS ==============
  'Home': 'ទំព័រដើម',
  'Schedule': 'កាលវិភាគ',
  'MyTeam': 'ក្រុមការងារ',
  'My Team': 'ក្រុមការងារ',
  'Request': 'សំណើ',
  'Requests': 'សំណើ',
  'Profile': 'គណនី',
  'Settings': 'ការកំណត់',
  'Face Attendance Settings': 'ការកំណត់ប្រព័ន្ធវត្តមានស្កេនមុខ',
  'Today\'s Attendance': 'វត្តមានថ្ងៃនេះ',
  'Clock In': 'កត់ត្រាចូល',
  'Clock Out': 'កត់ត្រាចេញ',
  'CHECK IN': 'កត់ត្រាចូល',
  'CHECK OUT': 'កត់ត្រាចេញ',
  'IN': 'ចូល',
  'OUT': 'ចេញ',
  'SESSION': 'វេន',
  'Session': 'វេន',
  'Session 1': 'វេនទី ១',
  'Session 2': 'វេនទី ២',
  'MORNING': 'ពេលព្រឹក',
  'AFTERNOON': 'ពេលរសៀល',
  'Morning': 'ពេលព្រឹក',
  'Afternoon': 'ពេលរសៀល',
  'Scheduled': 'តាមកាលវិភាគ',
  'In Progress': 'កំពុងដំណើរការ',
  'Completed': 'បានបញ្ចប់',
  'Completed for Today': 'បានបញ្ចប់សម្រាប់ថ្ងៃនេះ',
  'Absent': 'អវត្តមាន',
  'Open': 'បើក',
  'Upcoming': 'ពេលខាងមុខ',
  'Ready': 'រួចរាល់',
  'Register Face': 'ចុះឈ្មោះស្កេនផ្ទៃមុខ',
  'Register Face First': 'ចុះឈ្មោះស្កេនផ្ទៃមុខសិន',
  'Update Registered Face': 'ធ្វើបច្ចុប្បន្នភាពផ្ទៃមុខដែលបានចុះឈ្មោះ',
  'Enroll your face first': 'សូមចុះឈ្មោះស្កេនផ្ទៃមុខរបស់អ្នកជាមុនសិន',
  'Session 1 • Face or Tap ID': 'វេនទី ១ • ស្កេនមុខ ឬចុចកត់ត្រា',
  'Session 1 • Tap to check out': 'វេនទី ១ • ចុចដើម្បីកត់ត្រាចេញ',
  'Session 2 • Face or Tap ID': 'វេនទី ២ • ស្កេនមុខ ឬចុចកត់ត្រា',
  'Session 2 • Tap to finish shift': 'វេនទី ២ • ចុចដើម្បីបញ្ចប់ការងារ',
  'All Sessions Recorded': 'បានកត់ត្រាគ្រប់វេនទាំងអស់',
  'Request Time Adjustment': 'ស្នើសុំកែសម្រួលម៉ោង',
  'Daily Progress': 'វឌ្ឍនភាពប្រចាំថ្ងៃ',
  'Daily Goal': 'គោលដៅប្រចាំថ្ងៃ',
  'GOAL': 'គោលដៅ',
  'hrs': 'ម៉ោង',
  'hours': 'ម៉ោង',
  'Wi-Fi: Connected': 'Wi-Fi: បានភ្ជាប់',
  'Office Wi-Fi Connected': 'បានភ្ជាប់ Wi-Fi ការិយាល័យ',
  'Office Wi-Fi Not Connected': 'មិនទាន់បានភ្ជាប់ Wi-Fi ការិយាល័យ',
  'Wi-Fi Verification': 'ការផ្ទៀងផ្ទាត់ Wi-Fi',
  'Have a productive day': 'សូមឱ្យមានថ្ងៃធ្វើការប្រកបដោយប្រសិទ្ធភាព',
  'Good Morning': 'អរុណសួស្តី',
  'Good Afternoon': 'ទិវាសួស្តី',
  'Good Evening': 'សាយណ្ហសួស្តី',
  'Early Check-Out Alert': 'ការដាស់តឿនការចេញមុនម៉ោង',
  'Request Leave': 'ស្នើសុំច្បាប់ឈប់សម្រាក',
  'Check Out Now': 'កត់ត្រាចេញឥឡូវនេះ',
  'Cancel': 'បោះបង់',
  'CEO Management': 'ការគ្រប់គ្រងថ្នាក់ដឹកនាំ (CEO)',
  'Quick administrative actions': 'សកម្មភាពរដ្ឋបាលរហ័ស',
  'CLOCK ATTENDANCE': 'វត្តមានម៉ោងធ្វើការ',
  'Full View': 'មើលពេញលេញ',
  'CEO': 'អគ្គនាយក',
  'Manager': 'អ្នកគ្រប់គ្រង',
  'Leader': 'ប្រធានក្រុម',
  'Employee': 'បុគ្គលិក',
  'HR': 'ធនធានមនុស្ស',
  'Working Days': 'ថ្ងៃធ្វើការ',
  'Working Hours': 'ម៉ោងធ្វើការ',
  'Attendance Rate': 'អត្រាវត្តមាន',
  'Overtime Hours': 'ម៉ោងបន្ថែម',
  'Monthly Summary': 'សង្ខេបប្រចាំខែ',
  'Performance': 'លទ្ធផលការងារ',
  'Work Schedule': 'កាលវិភាគការងារ',
  'Worked': 'បានធ្វើការ',
  'Workday': 'ថ្ងៃធ្វើការ',
  'Day off': 'ថ្ងៃសម្រាក',
  'Leave': 'ច្បាប់ឈប់សម្រាក',
  'Overtime': 'ថែមម៉ោង',
  'No record': 'គ្មានទិន្នន័យ',
  'Days Present': 'ថ្ងៃមានវត្តមាន',
  'Days Absent': 'ថ្ងៃអវត្តមាន',
  'Leave Days': 'ថ្ងៃឈប់សម្រាក',
  'You\'re on track': 'អ្នកកំពុងស្ថិតលើគោលដៅល្អ',
  'Mon': 'ច័ន្ទ',
  'Tue': 'អង្គារ',
  'Wed': 'ពុធ',
  'Thu': 'ព្រហ',
  'Fri': 'សុក្រ',
  'Sat': 'សៅរ៍',
  'Sun': 'អាទិត្យ',
  'Search team members...': 'ស្វែងរកសមាជិកក្រុម...',
  'All': 'ទាំងអស់',
  'Present': 'មានវត្តមាន',
  'On Leave': 'ច្បាប់ឈប់សម្រាក',
  'Active': 'កំពុងបំពេញការងារ',
  'Team Attendance': 'វត្តមានក្រុមការងារ',
  'Total Members': 'សមាជិកសរុប',
  'Call': 'ខលទូរស័ព្ទ',
  'Message': 'ផ្ញើសារ',
  'Adjust Session Time': 'កែសម្រួលម៉ោងវេនការងារ',
  'Change Session Time': 'ផ្លាស់ប្តូរម៉ោងវេនការងារ',
  'No members found': 'រកមិនឃើញសមាជិកទេ',
  'Team Members': 'សមាជិកក្រុម',
  'Shift Details': 'ព័ត៌មានលម្អិតវេនការងារ',
  'Save Changes': 'រក្សាទុកការផ្លាស់ប្តូរ',
  'PENDING APPROVALS': 'សំណើរង់ចាំការអនុម័ត',
  'Pending': 'រង់ចាំការអនុម័ត',
  'Approved': 'បានអនុម័ត',
  'Rejected': 'បានបដិសេធ',
  'MANAGEMENT & SERVICES': 'ការគ្រប់គ្រង និងសេវាកម្ម',
  'My Schedule': 'កាលវិភាគរបស់ខ្ញុំ',
  'Leave Request': 'សំណើច្បាប់ឈប់សម្រាក',
  'Edit Leave Request': 'កែសម្រួលសំណើច្បាប់',
  'Overtime Request': 'សំណើធ្វើការបន្ថែមម៉ោង',
  'Edit Overtime Request': 'កែសម្រួលសំណើថែមម៉ោង',
  'Suggestion Box': 'ប្រអប់មតិយោបល់',
  'Submit Feedback': 'បញ្ជូនមតិយោបល់',
  'Feedback': 'មតិយោបល់',
  'History & Status': 'ប្រវត្តិ និងស្ថានភាព',
  'History & Pending': 'ប្រវត្តិ និងរង់ចាំអនុម័ត',
  'Permission & Authorization': 'ការអនុញ្ញាត និងការផ្ទៀងផ្ទាត់',
  'Permission': 'ការអនុញ្ញាត',
  'Request Permission': 'ស្នើសុំការអនុញ្ញាត',
  'Request Information': 'ព័ត៌មានសំណើ',
  'Request Detail': 'ព័ត៌មានលម្អិតនៃសំណើ',
  'Submit Request': 'ដាក់ស្នើសុំ',
  'Submit': 'ដាក់ស្នើ',
  'Reason': 'មូលហេតុ',
  'Reason / Note': 'មូលហេតុ / កំណត់សម្គាល់',
  'Enter your reason here...': 'សូមបញ្ចូលមូលហេតុនៅទីនេះ...',
  'Write your suggestion first.': 'សូមសរសេរសំណូមពររបស់អ្នកជាមុនសិន។',
  'Your suggestion was submitted.': 'សំណូមពររបស់អ្នកត្រូវបានបញ្ជូនរួចរាល់។',
  'From Date': 'ចាប់ពីថ្ងៃ',
  'To Date': 'ដល់ថ្ងៃ',
  'Date': 'កាលបរិច្ឆេទ',
  'Time': 'ពេលវេលា',
  'Start Time': 'ម៉ោងចាប់ផ្តើម',
  'End Time': 'ម៉ោងបញ្ចប់',
  'Duration': 'រយៈពេល',
  'Full Day': 'ពេញមួយថ្ងៃ',
  'Half Day': 'កន្លះថ្ងៃ',
  'Section 1': 'វេនទី ១',
  'Section 2': 'វេនទី ២',
  'Section 1 (Morning)': 'វេនទី ១ (ពេលព្រឹក)',
  'Section 2 (Afternoon)': 'វេនទី ២ (ពេលរសៀល)',
  'Early Leave': 'ចេញមុនម៉ោង',
  'Early Departure': 'ការចេញដំណើរមុនម៉ោង',
  'Attachment': 'ឯកសារភ្ជាប់',
  'Choose File': 'ជ្រើសរើសឯកសារ',
  'Change': 'ផ្លាស់ប្តូរ',
  'Remove': 'ដកចេញ',
  'Approve': 'អនុម័ត',
  'Reject': 'បដិសេធ',
  'Export PDF': 'ទាញយកជារបាយការណ៍ PDF',
  'Export Report': 'ទាញយករបាយការណ៍',
  'Download Report': 'ទាញយករបាយការណ៍',
  'This Month': 'ខែនេះ',
  'Last Month': 'ខែមុន',
  'Custom Range': 'ចន្លោះកាលបរិច្ឆេទជាក់លាក់',
  'Select Date Range': 'ជ្រើសរើសចន្លោះកាលបរិច្ឆេទ',
  'Select Date': 'ជ្រើសរើសកាលបរិច្ឆេទ',
  'No requests pending your review.': 'មិនមានសំណើរង់ចាំការត្រួតពិនិត្យរបស់អ្នកទេ។',
  'No requests found': 'រកមិនឃើញសំណើទេ',
  'ATTENDANCE CALENDAR': 'ប្រតិទិនវត្តមាន',
  'FACE BIOMETRICS': 'ជីវមាត្រផ្ទៃមុខ',
  'PREFERENCES': 'ចំណូលចិត្ត',
  'ACCOUNT': 'គណនី',
  'ROLE-BASED PANEL ACCESS': 'ការចូលប្រើប្រាស់តាមតួនាទី',
  'All Authorized': 'ទទួលបានការអនុញ្ញាតទាំងអស់',
  'CEO Control Panel': 'ផ្ទាំងបញ្ជាអគ្គនាយក (CEO)',
  'Full system oversight and executive controls': 'ការត្រួតពិនិត្យប្រព័ន្ធពេញលេញ និងការគ្រប់គ្រងថ្នាក់ដឹកនាំ',
  'Manager Portal': 'ផ្ទាំងអ្នកគ្រប់គ្រង',
  'Team management & approval workflows': 'ការគ្រប់គ្រងក្រុម និងលំហូរការអនុម័ត',
  'Leader View': 'ផ្ទាំងប្រធានក្រុម',
  'Direct team oversight & task delegation': 'ការត្រួតពិនិត្យក្រុមផ្ទាល់ និងការចាត់ចែងការងារ',
  'Employee Workspace': 'កន្លែងធ្វើការបុគ្គលិក',
  'Personal dashboard & self-service tools': 'ផ្ទាំងព័ត៌មានផ្ទាល់ខ្លួន និងឧបករណ៍ស្វ័យសេវា',
  'Face biometrics enrolled • Tap to re-scan': 'បានចុះឈ្មោះជីវមាត្រមុខរួចហើយ • ចុចដើម្បីស្កេនឡើងវិញ',
  'Face biometrics required • Tap to enroll now': 'តម្រូវឱ្យចុះឈ្មោះស្កេនមុខ • ចុចដើម្បីចុះឈ្មោះឥឡូវនេះ',
  'Settings & Language': 'ការកំណត់ និងភាសា',
  'English (US) • Notifications': 'ភាសាអង់គ្លេស • ការជូនដំណឹង',
  'Khmer • Notifications': 'ភាសាខ្មែរ • ការជូនដំណឹង',
  'Log Out': 'ចាកចេញពីគណនី',
  'Are you sure you want to log out of your account?': 'តើអ្នកពិតជាចង់ចាកចេញពីគណនីរបស់អ្នកមែនទេ?',
  'Updating profile picture...': 'កំពុងធ្វើបច្ចុប្បន្នភាពរូបភាពកម្រងព័ត៌មាន...',
  'Profile picture updated successfully!': 'រូបភាពកម្រងព័ត៌មានត្រូវបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ!',
  'LANGUAGE / ភាសា': 'ភាសា / LANGUAGE',
  'LANGUAGE': 'ភាសា',
  'Language': 'ភាសា',
  'App content and interface language': 'ភាសាសម្រាប់មាតិកា និងចំណុចប្រទាក់កម្មវិធី',
  'ABOUT': 'អំពីកម្មវិធី',
  'About': 'អំពីកម្មវិធី',
  'Terms of Service': 'លក្ខខណ្ឌប្រើប្រាស់',
  'Privacy Policy': 'គោលការណ៍ភាពឯកជន',
  'Support & Documentation': 'ជំនួយ និងឯកសារណែនាំ',
  'Latest': 'ចុងក្រោយបំផុត',
  'Notifications': 'ការជូនដំណឹង',
  'Mark all as read': 'សម្គាល់ថាបានអានទាំងអស់',
  'Clear all': 'សម្អាតទាំងអស់',
  'No notifications': 'មិនមានការជូនដំណឹងទេ',
  'No notifications yet': 'មិនទាន់មានការជូនដំណឹងនៅឡើយទេ',
  'Executive Actions': 'សកម្មភាពថ្នាក់ដឹកនាំ',
  'System configuration and resource creation': 'ការកំណត់រចនាសម្ព័ន្ធប្រព័ន្ធ និងការបង្កើតធនធាន',
  'Biometric Security & Anti-Spoofing': 'សុវត្ថិភាពជីវមាត្រ និងប្រព័ន្ធការពារការក្លែងបន្លំ',
  'kby-ai on-device matching engine': 'ម៉ាស៊ីនផ្ទៀងផ្ទាត់ kby-ai លើឧបករណ៍ផ្ទាល់',
  'Organization Overview': 'ទិដ្ឋភាពទូទៅនៃស្ថាប័ន',
  'Total Employees': 'បុគ្គលិកសរុប',
  'Today Attendance': 'វត្តមានថ្ងៃនេះ',
  'Create Employee': 'បង្កើតបុគ្គលិកថ្មី',
  'Create Branch': 'បង្កើតសាខាថ្មី',
  'Create Department': 'បង្កើតផ្នែកថ្មី',
  'Employee List': 'បញ្ជីបុគ្គលិក',
  'Branches': 'សាខា',
  'Departments': 'ផ្នែក / នាយកដ្ឋាន',
  'Refresh Telemetry': 'ផ្ទុកទិន្នន័យឡើងវិញ',
  'Face Attendance Security Suite': 'ប្រព័ន្ធសុវត្ថិភាពវត្តមានស្កេនមុខ',
  'All rights reserved.': 'រក្សាសិទ្ធិគ្រប់យ៉ាង។',
  'English': 'English',
  'Khmer': 'ភាសាខ្មែរ',
  'Success': 'ជោគជ័យ',
  'Error': 'មានបញ្ហា',
  'Warning': 'ការព្រមាន',
  'OK': 'យល់ព្រម',
  'Yes': 'បាទ / ចាស',
  'No': 'ទេ',
  'Save': 'រក្សាទុក',
  'Delete': 'លុប',
  'Edit': 'កែប្រែ',
  'Close': 'បិទ',
  'Loading...': 'កំពុងផ្ទុក...',
  'Try Again': 'ព្យាយាមម្តងទៀត',
  'No data available': 'មិនមានទិន្នន័យ',

  // Additional screen literals
  'TOTAL HOURS WORKED': 'ម៉ោងធ្វើការសរុប',
  'Goal Reached!': 'សម្រេចគោលដៅ!',
  'Done!': 'រួចរាល់!',
  'remaining': 'នៅសល់',
  'of 8.0h goal': 'នៃគោលដៅ ៨.០ ម៉ោង',
  'Office Wi-Fi Connected • Main HQ': 'បានភ្ជាប់វ៉ាយហ្វាយការិយាល័យ • ទីស្នាក់ការកណ្តាល',
  'Executive Attendance': 'វត្តមានថ្នាក់ដឹកនាំ',
  'All Shifts Recorded': 'បានកត់ត្រាវត្តមានពេញលេញ',
  'Clocked In • Shift in progress': 'បានកត់ចូល • កំពុងបម្រើការងារ',
  'Ready to Clock In': 'រួចរាល់ក្នុងការកត់វត្តមានចូល',
  'TODAY\'S SHIFT': 'វេនការងារថ្ងៃនេះ',
  'WORKED': 'ធ្វើការបាន',
  'Full telemetry, biometric controls & organization oversight': 'ការត្រួតពិនិត្យប្រព័ន្ធទូទៅ ការគ្រប់គ្រងជីវមាត្រ និងរចនាសម្ព័ន្ធ',
  'Set up branch location & GPS geofence': 'កំណត់ទីតាំងសាខា និងកាំ GPS',
  'Add department to an existing branch': 'បន្ថែមផ្នែកទៅក្នុងសាខាដែលមានស្រាប់',
  'Create User': 'បង្កើតគណនីអ្នកប្រើ',
  'Invite Manager, Leader, or Employee': 'អញ្ជើញអ្នកគ្រប់គ្រង ប្រធានក្រុម ឬបុគ្គលិក',
  'Created Branches': 'សាខាដែលបានបង្កើត',
  'Created Departments': 'ផ្នែកដែលបានបង្កើត',
  'Invited Users': 'អ្នកប្រើប្រាស់ដែលបានអញ្ជើញ',
  'View All': 'មើលទាំងអស់',
  'Radius': 'កាំចម្ងាយ',
  'geofence': 'ដែនកំណត់ទីតាំង',
  'staff': 'បុគ្គលិក',
  'Branch': 'សាខា',
  'Employees': 'បុគ្គលិក',
  'Face ID Registered': 'បានចុះឈ្មោះស្កេនមុខរួចហើយ',
  'Face ID Not Registered': 'មិនទាន់បានចុះឈ្មោះស្កេនមុខទេ',
  'Sign out of your session on this device': 'ចាកចេញពីគណនីរបស់អ្នកលើឧបករណ៍នេះ',
  'Calendar View': 'ទិដ្ឋភាពប្រតិទិន',
  'Absence Permission Info': 'ព័ត៌មានលម្អិតអំពីការអនុញ្ញាតច្បាប់',
  'Permitted': 'បានអនុញ្ញាត',
  'Leave Type': 'ប្រភេទច្បាប់',
  'Approved By': 'អនុម័តដោយ',
  'Time Range': 'ចន្លោះពេល',
  'Documentation': 'ឯកសារយោង',
  'This absence has verified management permission and does not reduce attendance rating.': 'ការអវត្តមាននេះមានការអនុញ្ញាតត្រឹមត្រូវពីថ្នាក់លើ និងមិនប៉ះពាល់ដល់ពិន្ទុវត្តមានទេ។',
  'Got It': 'យល់ព្រម',
  'Tap to view leave details': 'ចុចដើម្បីមើលព័ត៌មានច្បាប់',
  'Tap to view permission reason': 'ចុចដើម្បីមើលមូលហេតុអនុញ្ញាត',
  'days worked': 'ថ្ងៃបានធ្វើការ',
  'complete': 'បានបញ្ចប់',
  'days to go': 'ថ្ងៃនៅសល់',
  'Days Goal': 'គោលដៅថ្ងៃ',
  'On-Time Rate': 'អត្រាទៀងទាត់ពេល',
  'Limit': 'ដែនកំណត់',
  'Holiday': 'ថ្ងៃឈប់សម្រាក',
  'No Shifts Scheduled': 'មិនមានកាលវិភាគការងារទេ',
  'No scheduled shifts found for this period.': 'រកមិនឃើញកាលវិភាគវេនការងារក្នុងអំឡុងពេលនេះទេ។',
  'Nothing here yet': 'មិនទាន់មានទិន្នន័យនៅឡើយទេ',
  'Public holidays will appear here once they are added.': 'ថ្ងៃឈប់សម្រាកបុណ្យជាតិនឹងបង្ហាញនៅទីនេះពេលមានការបញ្ចូល។',
  'Your leave days will appear here once they are approved.': 'ថ្ងៃច្បាប់សម្រាករបស់អ្នកនឹងបង្ហាញនៅទីនេះបន្ទាប់ពីទទួលបានការអនុម័ត។',
  'h': 'ម៉ោង',
  'Pinned': 'បានខ្ទាស់ទុក',
  'Search by name, role, or branch': 'ស្វែងរកតាមឈ្មោះ តួនាទី ឬសាខា',
  'No team members found': 'រកមិនឃើញសមាជិកក្រុមទេ',
  'Try searching by a different name, role, or branch.': 'សូមសាកល្បងស្វែងរកតាមឈ្មោះ តួនាទី ឬសាខាផ្សេងទៀត។',
  'Failed to load team data': 'មិនអាចទាញយកទិន្នន័យក្រុមបានទេ',
  'Retry': 'ព្យាយាមម្តងទៀត',
  'Unpin': 'ដោះការខ្ទាស់',
  'Pin': 'ខ្ទាស់ទុក',
  'No phone number available': 'មិនមានលេខទូរស័ព្ទទេ',
  'Apply': 'ស្នើសុំ',
  'REQUEST ACTIVITY': 'សកម្មភាពនៃសំណើ',
  'History': 'ប្រវត្តិ',
  'Unauthorized': 'មិនទាន់អនុម័ត',
  'Pending review': 'រង់ចាំការពិនិត្យ',
  'Authorized': 'បានអនុម័តរួចរាល់',
  'Completed & archived': 'បានបញ្ចប់ និងរក្សាទុក',
  'Total': 'សរុប',
  'Session 1 • Morning': 'វេនទី ១ • ពេលព្រឹក',
  'Session 2 • Afternoon': 'វេនទី ២ • ពេលរសៀល',
  'All Sessions Done': 'បានបញ្ចប់គ្រប់វេនការងារ',
  'Done': 'រួចរាល់',
  'Setup': 'រៀបចំ',
  'January': 'មករា',
  'February': 'កុម្ភៈ',
  'March': 'មីនា',
  'April': 'មេសា',
  'May': 'ឧសភា',
  'June': 'មិថុនា',
  'July': 'កក្កដា',
  'August': 'សីហា',
  'September': 'កញ្ញា',
  'October': 'តុលា',
  'November': 'វិច្ឆិកា',
  'December': 'ធ្នូ',
  'Monday': 'ចន្ទ',
  'Tuesday': 'អង្គារ',
  'Wednesday': 'ពុធ',
  'Thursday': 'ព្រហស្បតិ៍',
  'Friday': 'សុក្រ',
  'Saturday': 'សៅរ៍',
  'Sunday': 'អាទិត្យ',

  // Session Time Dialog & My Team
  'Total Daily Scheduled Work:': 'ការងារគ្រោងសរុបប្រចាំថ្ងៃ:',
  'Session 1 (Morning Shift)': 'វេនទី ១ (វេនព្រឹក)',
  'Session 2 (Afternoon Shift)': 'វេនទី ២ (វេនរសៀល)',
  'ACTIVE WORK DAYS': 'ថ្ងៃធ្វើការសកម្ម',
  'Mon-Fri': 'ច័ន្ទ-សុក្រ',
  'Save Session Schedule': 'រក្សាទុកកាលវិភាគវេន',
  'Start (Check-in)': 'ចាប់ផ្តើម (ចូល)',
  'End (Check-out)': 'បញ្ចប់ (ចេញ)',
  'Session 1: End time must be after start time.': 'វេនទី ១: ម៉ោងបញ្ចប់ត្រូវតែក្រោយម៉ោងចាប់ផ្តើម។',
  'Session 2: Cannot start before Session 1 ends.': 'វេនទី ២: មិនអាចចាប់ផ្តើមមុនវេនទី ១ បញ្ចប់ទេ។',
  'Session 2: End time must be after start time.': 'វេនទី ២: ម៉ោងបញ្ចប់ត្រូវតែក្រោយម៉ោងចាប់ផ្តើម។',
  'Please select at least one active work day.': 'សូមជ្រើសរើសយ៉ាងហោចណាស់មួយថ្ងៃធ្វើការសកម្ម។',
  'Session Updated': 'បានធ្វើបច្ចុប្បន្នភាពវេន',
  'Work schedule was successfully updated.': 'កាលវិភាគការងារត្រូវបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ។',
  'SESSION 1': 'វេនទី ១',
  'SESSION 2': 'វេនទី ២',
  'Request permissions or authorization changes': 'ស្នើសុំការអនុញ្ញាត ឬការផ្លាស់ប្តូរសិទ្ធិ',
  'Permission Request': 'ពាក្យស្នើសុំការអនុញ្ញាត',
  'Days Worked': 'ថ្ងៃបានធ្វើការ',
  'Early leave at': 'ចេញមុនម៉ោងនៅ',
  'Full Day Leave': 'ច្បាប់ពេញមួយថ្ងៃ',
  'on': 'នៅថ្ងៃ',
  'CEO Hub': 'មជ្ឈមណ្ឌល CEO',
  'Manager Hub': 'មជ្ឈមណ្ឌលអ្នកគ្រប់គ្រង',
  'Leader Hub': 'មជ្ឈមណ្ឌលប្រធានក្រុម',
  'Executive Administration & Shifts': 'ការគ្រប់គ្រងថ្នាក់ដឹកនាំ និងវេនការងារ',
  'Organization & Team Actions': 'សកម្មភាពស្ថាប័ន និងក្រុម',
  'Team Growth & Invites': 'ការរីកចម្រើនក្រុម និងការអញ្ជើញ',
  'Manage organizational departments, change user session times, and coordinate staff.': 'គ្រប់គ្រងនាយកដ្ឋានស្ថាប័ន ប្តូរម៉ោងវេនការងារ និងសម្របសម្រួលបុគ្គលិក។',
  'Create departments and invite Leaders or Employees to your organization.': 'បង្កើតនាយកដ្ឋាន និងអញ្ជើញប្រធានក្រុម ឬបុគ្គលិកមកកាន់ស្ថាប័នរបស់អ្នក។',
  'Invite new Employees to join your operational team.': 'អញ្ជើញបុគ្គលិកថ្មីឱ្យចូលរួមក្នុងក្រុមការងារប្រតិបត្តិការរបស់អ្នក។',
  'QUICK ACTIONS': 'សកម្មភាពរហ័ស',
  'DIRECTORIES': 'បញ្ជីព័ត៌មាន',
  'Invite Staff / Manager': 'អញ្ជើញបុគ្គលិក / អ្នកគ្រប់គ្រង',
  'Invite User': 'អញ្ជើញអ្នកប្រើប្រាស់',
  'Invite Employee': 'អញ្ជើញបុគ្គលិក',
  'Invite a Manager, Leader, or Employee': 'អញ្ជើញអ្នកគ្រប់គ្រង ប្រធានក្រុម ឬបុគ្គលិក',
  'Invite a Leader or Employee to join': 'អញ្ជើញប្រធានក្រុម ឬបុគ្គលិកឱ្យចូលរួម',
  'Invite a new Employee to your team': 'អញ្ជើញបុគ្គលិកថ្មីមកកាន់ក្រុមរបស់អ្នក',
  'Departments List': 'បញ្ជីនាយកដ្ឋាន',
  'View and manage created departments': 'មើល និងគ្រប់គ្រងនាយកដ្ឋានដែលបានបង្កើត',
  'Staff & Session Schedules': 'បុគ្គលិក និងកាលវិភាគវេន',
  'Staff & Users Directory': 'បញ្ជីបុគ្គលិក និងអ្នកប្រើប្រាស់',
  'Team Directory': 'បញ្ជីក្រុមការងារ',
  'View staff profiles, change session times, and manage users': 'មើលព័ត៌មានបុគ្គលិក ប្តូរម៉ោងវេនការងារ និងគ្រប់គ្រងអ្នកប្រើប្រាស់',
  'View staff, resend invitations, and manage members': 'មើលបុគ្គលិក ផ្ញើការអញ្ជើញឡើងវិញ និងគ្រប់គ្រងសមាជិក',
  'Both Shifts': 'វេនទាំងពីរ',
  'Leave Option for': 'ជម្រើសច្បាប់សម្រាកសម្រាប់',
  'Full': 'ពេញ',
  'Leave Early': 'ចេញមុនម៉ោង',
  'Departure Time': 'ម៉ោងចេញដំណើរ',
  'Target Workday': 'ថ្ងៃធ្វើការគោលដៅ',
  'Today • Workday': 'ថ្ងៃនេះ • ថ្ងៃធ្វើការ',
  'Selected Date': 'កាលបរិច្ឆេទដែលបានជ្រើស',
  'Work Section to Leave': 'វេនការងារដែលត្រូវសុំច្បាប់',
  'Full Day Leave excuses both morning (Section 1) and afternoon (Section 2) shifts.': 'ច្បាប់ពេញមួយថ្ងៃអនុញ្ញាតឱ្យឈប់ទាំងវេនព្រឹក (វេនទី ១) និងវេនរសៀល (វេនទី ២)។',
  'Max 250 characters': 'អតិបរមា ២៥០ តួអក្សរ',
  'Please provide details about your leave request...': 'សូមផ្តល់ព័ត៌មានលម្អិតអំពីសំណើច្បាប់សម្រាករបស់អ្នក...',
  'Attach Document or Image (PDF, JPG, PNG)': 'ភ្ជាប់ឯកសារ ឬរូបភាព (PDF, JPG, PNG)',
  'Update Leave Request': 'ធ្វើបច្ចុប្បន្នភាពសំណើច្បាប់',
  'Submit Leave Request': 'ដាក់ស្នើសុំច្បាប់សម្រាក',
  'Submitting...': 'កំពុងដាក់ស្នើ...',
  'Requests require approval from your direct manager': 'សំណើតម្រូវឱ្យមានការអនុម័តពីអ្នកគ្រប់គ្រងផ្ទាល់របស់អ្នក',
  'No Leave Requests Yet': 'មិនទាន់មានសំណើច្បាប់សម្រាកនៅឡើយទេ',
  'Your submitted leave requests will appear here with live review status.': 'សំណើច្បាប់ដែលអ្នកបានដាក់ស្នើនឹងបង្ហាញនៅទីនេះជាមួយស្ថានភាពជាក់ស្តែង។',
  'Review note:': 'កំណត់សម្គាល់ការពិនិត្យ:',
  'View Details': 'មើលព័ត៌មានលម្អិត',
  'Cancel Request': 'បោះបង់សំណើ',
  'Are you sure you want to cancel this leave request?': 'តើអ្នកប្រាកដជាចង់បោះបង់សំណើច្បាប់សម្រាកនេះឬ?',
  'Keep': 'រក្សាទុក',
  'Yes, Cancel': 'បាទ/ចាស បោះបង់',
  'Full Day (Both Sections)': 'ពេញមួយថ្ងៃ (វេនទាំងពីរ)',
  'Total Days': 'ថ្ងៃសរុប',
  'Leave Time': 'ម៉ោងសុំច្បាប់',
  'Supporting Document': 'ឯកសារគាំទ្រ',
  'Reviewed By': 'ពិនិត្យដោយ',
  'Review Notes': 'កំណត់សម្គាល់ការពិនិត្យ',
  'MONTH ALLOWANCE': 'កូតាប្រចាំខែ',
  'Used': 'បានប្រើ',
  'Quota Filled': 'បំពេញកូតា',
  'hrs remaining': 'ម៉ោងនៅសល់',
  'SHIFT INTERVAL': 'ចន្លោះពេលវេន',
  'DURATION': 'រយៈពេល',
  'Total Overtime': 'ថែមម៉ោងសរុប',
  'Submit Overtime Request': 'ដាក់ស្នើសុំធ្វើការបន្ថែមម៉ោង',
  'Update Overtime Request': 'ធ្វើបច្ចុប្បន្នភាពសំណើថែមម៉ោង',
  'No Overtime Requests Yet': 'មិនទាន់មានសំណើថែមម៉ោងនៅឡើយទេ',
  'Your submitted overtime requests will appear here with review status.': 'សំណើថែមម៉ោងដែលអ្នកបានដាក់ស្នើនឹងបង្ហាញនៅទីនេះជាមួយស្ថានភាពពិនិត្យ។',
  'Overtime Guidelines': 'គោលការណ៍ណែនាំការថែមម៉ោង',
  'Understood': 'យល់ព្រម',
  'Download PDF Report': 'ទាញយករបាយការណ៍ PDF',
  'Help': 'ជំនួយ',
  'Anything we can do better?': 'តើយើងអាចកែលម្អអ្វីខ្លះឱ្យកាន់តែប្រសើរ?',
  'Even the smallest suggestion can help us improve together': 'សូម្បីតែមតិយោបល់តូចមួយ ក៏អាចជួយឱ្យយើងរីកចម្រើនទាំងអស់គ្នា',
  'CATEGORY': 'ប្រភេទ',
  'Workplace & Equipment': 'កន្លែងធ្វើការ និងបរិក្ខារ',
  'Shift Schedule': 'កាលវិភាគវេន',
  'Team Culture': 'វប្បធម៌ការងារជាក្រុម',
  'Other': 'ផ្សេងៗ',
  'YOUR SUGGESTION': 'សំណូមពររបស់អ្នក',
  'Share your thoughts, suggestions, or concerns...': 'ចែករំលែកការគិត សំណូមពរ ឬការព្រួយបារម្ភរបស់អ្នក...',
  'Constructive feedback is shared directly with ops': 'មតិស្ថាបនានឹងត្រូវបញ្ជូនដោយផ្ទាល់ទៅកាន់ផ្នែកប្រតិបត្តិការ',
  'Submit anonymously': 'ដាក់ស្នើដោយមិនបញ្ចេញឈ្មោះ',
  'Your identity will not be attached': 'អត្តសញ្ញាណរបស់អ្នកនឹងមិនត្រូវបានបង្ហាញឡើយ',
  'No suggestions yet': 'មិនទាន់មានសំណូមពរនៅឡើយទេ',
  'Delete suggestion?': 'លុបសំណូមពរ?',
  'This cannot be undone.': 'សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។',
  'Your Message': 'សាររបស់អ្នក',
  'Mark as seen?': 'សម្គាល់ថាបានមើលរួច?',
  'Mark as seen': 'សម្គាល់ថាបានមើល',
  'The employee will no longer be able to edit this suggestion.': 'បុគ្គលិកនឹងមិនអាចកែប្រែសំណូមពរនេះបានទៀតទេ។',
  'Pending Request': 'សំណើរង់ចាំការពិនិត្យ',
  'Completed Request': 'សំណើបានបញ្ចប់',
  'Pick Date': 'ជ្រើសរើសកាលបរិច្ឆេទ',
  'Back to session list': 'ត្រឡប់ទៅបញ្ជីវេន',
  'Add another session': 'បន្ថែមវេនមួយទៀត',
  'Request List': 'បញ្ជីសំណើ',
  'No added request': 'មិនទាន់មានសំណើដែលបានបន្ថែម',
  'No pending requests': 'មិនមានសំណើរង់ចាំទេ',
  'No approved requests': 'មិនមានសំណើបានអនុម័តទេ',
  'Save changes': 'រក្សាទុកការផ្លាស់ប្តូរ',
  'Keep request': 'រក្សាទុកសំណើ',
  'Yes, cancel': 'បាទ/ចាស បោះបង់',
  'Change this approved request?': 'ផ្លាស់ប្តូរសំណើដែលបានអនុម័តនេះ?',
  'After you save, the request goes back to Pending and needs approval again.': 'បន្ទាប់ពីរៀបចំរួច សំណើនឹងត្រឡប់ទៅរង់ចាំការពិនិត្យ និងត្រូវការអនុម័តម្តងទៀត។',
  'Keep as approved': 'រក្សាទុកដូចការអនុម័ត',
  'Yes, change it': 'បាទ/ចាស ផ្លាស់ប្តូរវា',
  'This date has already passed, so the request can no longer be changed.': 'កាលបរិច្ឆេទនេះបានកន្លងផុតទៅហើយ ដូច្នេះសំណើមិនអាចកែប្រែបានទៀតទេ។',
  'Mark all read': 'សម្គាល់ថាបានអានទាំងអស់',
  'You will be notified about request updates and approvals here.': 'អ្នកនឹងទទួលបានការជូនដំណឹងអំពីបច្ចុប្បន្នភាពសំណើ និងការអនុម័តនៅទីនេះ។',
  'Align your face within the frame': 'សូមតម្រឹមមុខរបស់អ្នកឱ្យចំក្នុងស៊ុម',
  'GPS Ready': 'GPS រួចរាល់',
  'Locating...': 'កំពុងស្វែងរកទីតាំង...',
  'Retry Camera Connection': 'ភ្ជាប់កាមេរ៉ាម្តងទៀត',
  'Success!': 'ជោគជ័យ!',
  'Biometric Match:': 'ភាពត្រូវគ្នានៃជីវមាត្រ:',
  'Liveness Score:': 'ពិន្ទុជីវមាត្រពិត:',
  'Security Alert: Biometric Mismatch': 'ការប្រុងប្រយ័ត្នសន្តិសុខ: ជីវមាត្រមិនត្រូវគ្នា',
  'Face Verification Failed': 'ការផ្ទៀងផ្ទាត់ផ្ទៃមុខបានបរាជ័យ',
  'Outside Check-In Window': 'ក្រៅម៉ោងចូលបំពេញការងារ',
  'Location Out of Range': 'ទីតាំងនៅក្រៅដែនកំណត់',
  'Total Duration:': 'រយៈពេលសរុប៖',
  'REASON FOR OVERTIME': 'មូលហេតុនៃការថែមម៉ោង',
  'Please write your detailed reason here...': 'សូមសរសេរមូលហេតុលម្អិតរបស់អ្នកនៅទីនេះ...',
  'Attach Work Log or Task Screenshot (PDF, JPG, PNG)': 'ភ្ជាប់កំណត់ហេតុការងារ ឬរូបថតអេក្រង់កិច្ចការ (PDF, JPG, PNG)',
  'Requests are subject to manager approval within 24 hours.': 'សំណើត្រូវឆ្លងកាត់ការអនុម័តពីអ្នកគ្រប់គ្រងក្នុងរយៈពេល ២៤ ម៉ោង។',
  'Monthly Attendance Report': 'របាយការណ៍វត្តមានប្រចាំខែ',
  'Export overtime summary as PDF': 'នាំចេញសេចក្តីសង្ខេបការថែមម៉ោងជា PDF',
  'Export': 'នាំចេញ',
  'No Overtime Requests': 'មិនមានសំណើថែមម៉ោងទេ',
  'Submitted overtime logs and approval updates will appear here.': 'កំណត់ហេតុថែមម៉ោងដែលបានដាក់ និងការធ្វើបច្ចុប្បន្នភាពការអនុម័តនឹងបង្ហាញនៅទីនេះ។',
  'From Time': 'ចាប់ពីម៉ោង',
  'To Time': 'រហូតដល់ម៉ោង',
  'h of 20h Used': 'ម៉ោង ក្នុងចំណោម ២០ម៉ោង បានប្រើ',
  'overtime_guidelines_body':
      '• កូតាថែមម៉ោងស្តង់ដារប្រចាំខែគឺ ២០ ម៉ោងក្នុងមួយបុគ្គលិក។\n• សំណើថែមម៉ោងត្រូវបញ្ជាក់ពីហេតុផលអាជីវកម្ម និងកិច្ចការដែលបានធ្វើឱ្យបានច្បាស់លាស់។\n• សំណើនឹងត្រូវបានត្រួតពិនិត្យ និងអនុម័តដោយអ្នកគ្រប់គ្រងផ្ទាល់របស់អ្នកក្នុងរយៈពេល ២៤ ម៉ោង។\n• របាយការណ៍ប្រចាំខែអាចទាញយកជាទម្រង់ PDF ពីផ្ទាំងប្រវត្តិ។',
  'This request could not be found.': 'រកមិនឃើញសំណើនេះទេ។',
  '0 minutes': '០ នាទី',
  'minute': 'នាទី',
  'minutes': 'នាទី',
  '0 HOURS': '០ ម៉ោង',
  'HOUR': 'ម៉ោង',
  'HOURS': 'ម៉ោង',
  'KB • Tap Change to replace': 'KB • ចុចផ្លាស់ប្តូរដើម្បីជំនួស',
  'Enter the reason for the overtime.': 'សូមបញ្ចូលមូលហេតុនៃការថែមម៉ោង។',
  'To time must be after from time.': 'ម៉ោងបញ្ចប់ត្រូវតែនៅក្រោយម៉ោងចាប់ផ្តើម។',
  'Your overtime request was updated.': 'សំណើថែមម៉ោងរបស់អ្នកត្រូវបានធ្វើបច្ចុប្បន្នភាព។',
  'This request was already approved, so it cannot be edited.': 'សំណើនេះត្រូវបានអនុម័តរួចហើយ ដូច្នេះមិនអាចកែសម្រួលបានទេ។',
  'Overtime request submitted.': 'សំណើថែមម៉ោងត្រូវបានដាក់ស្នើ។',
  'Attachment removed.': 'បានលុបឯកសារភ្ជាប់ចេញ។',
  'Could not create the PDF. Please try again.': 'មិនអាចបង្កើត PDF បានទេ។ សូមព្យាយាមម្តងទៀត។',
  'From:': 'ពី៖',
  'Just now': 'ទើបតែឥឡូវនេះ',
  'm ago': ' នាទីមុន',
  'h ago': ' ម៉ោងមុន',
  'd ago': ' ថ្ងៃមុន',
  'Upload Photo Instead': 'បង្ហោះរូបថតជំនួសវិញ',
  'Camera loading or permission required': 'កំពុងដំណើរការកាមេរ៉ា ឬទាមទារការអនុញ្ញាត',
  'Please ensure your camera is connected and permitted to enroll your face biometric.': 'សូមប្រាកដថាកាមេរ៉ារបស់អ្នកត្រូវបានភ្ជាប់ និងអនុញ្ញាតដើម្បីចុះឈ្មោះផ្ទៃមុខ។',
  'You can capture using your webcam or upload a clear photo of your face directly from your computer.': 'អ្នកអាចចាប់យករូបភាពដោយប្រើកាមេរ៉ា ឬបង្ហោះរូបថតផ្ទៃមុខច្បាស់ពីកុំព្យូទ័ររបស់អ្នក។',
  'Upload Photo for': 'បង្ហោះរូបថតសម្រាប់',
  'Check In': 'ចុះវត្តមានចូល',
  'Check Out': 'ចុះវត្តមានចេញ',
  'Face Attendance': 'វត្តមានផ្ទៃមុខ',
  'Scanning and processing face...': 'កំពុងស្កេន និងដំណើរការផ្ទៃមុខ...',
  'Extracting biometric face features on-device...': 'កំពុងស្រង់ទិន្នន័យជីវមាត្រផ្ទៃមុខលើឧបករណ៍...',
  'Matching face biometrics & geofence on-device...': 'កំពុងផ្គូផ្គងជីវមាត្រផ្ទៃមុខ និងទីតាំងលើឧបករណ៍...',
  'Matching face biometrics for check-out on-device...': 'កំពុងផ្គូផ្គងជីវមាត្រផ្ទៃមុខសម្រាប់ចុះចេញលើឧបករណ៍...',
  'Waiting for GPS fix. Please ensure location is enabled.': 'កំពុងរង់ចាំសញ្ញា GPS។ សូមប្រាកដថាទីតាំងត្រូវបានបើក។',
  'Location Required': 'ទាមទារទីតាំង',
  'Operation completed successfully.': 'ប្រតិបត្តិការបានបញ្ចប់ដោយជោគជ័យ។',
  'Your suggestion was updated.': 'ការផ្ដល់យោបល់របស់អ្នកត្រូវបានធ្វើបច្ចុប្បន្នភាព។',
  'This suggestion was already seen, so it cannot be edited.': 'ការផ្ដល់យោបល់នេះត្រូវបានមើលរួចហើយ ដូច្នេះមិនអាចកែសម្រួលបានទេ។',
  'Suggestion deleted.': 'បានលុបការផ្ដល់យោបល់រួចរាល់។',
  'This suggestion was already seen, so it cannot be deleted.': 'ការផ្ដល់យោបល់នេះត្រូវបានមើលរួចហើយ ដូច្នេះមិនអាចលុបបានទេ។',
  'Suggestion marked as seen.': 'ការផ្ដល់យោបល់ត្រូវបានសម្គាល់ថាបានមើល។',
  'Pick a date first.': 'សូមជ្រើសរើសកាលបរិច្ឆេទជាមុនសិន។',
  'Enter the reason for your request.': 'សូមបញ្ចូលមូលហេតុនៃសំណើរបស់អ្នក។',
  'You already have a request for that date and schedule.': 'អ្នកមានសំណើសម្រាប់កាលបរិច្ឆេទ និងកាលវិភាគនោះរួចហើយ។',
  'Add at least one session before submitting.': 'សូមបន្ថែមយ៉ាងហោចណាស់វេនមួយមុនពេលដាក់ស្នើ។',
  'Your permission request was submitted.': 'សំណើសុំការអនុញ្ញាតរបស់អ្នកត្រូវបានដាក់ស្នើ។',
  'Saved. The request is Pending again and needs approval.': 'បានរក្សាទុក។ សំណើបានត្រឡប់ទៅរង់ចាំម្តងទៀត និងត្រូវការការអនុម័ត។',
  'Your changes were saved.': 'ការផ្លាស់ប្តូររបស់អ្នកត្រូវបានរក្សាទុក។',
  'Your request was cancelled.': 'សំណើរបស់អ្នកត្រូវបានបោះបង់។',
  'Branch Management': 'ការគ្រប់គ្រងសាខា',
  'Add New Branch': 'បន្ថែមសាខាថ្មី',
  'No branches found': 'រកមិនឃើញសាខាទេ',
  'Create a branch to configure geofence attendance.': 'បង្កើតសាខាដើម្បីកំណត់ទីតាំងវត្តមាន geofence។',
  'Department Management': 'ការគ្រប់គ្រងផ្នែក',
  'Add New Department': 'បន្ថែមផ្នែកថ្មី',
  'No departments found': 'រកមិនឃើញផ្នែកទេ',
  'Create a department to group your staff members.': 'បង្កើតផ្នែកដើម្បីរៀបចំក្រុមបុគ្គលិករបស់អ្នក។',
  'Employee Directory': 'បញ្ជីឈ្មោះបុគ្គលិក',
  'Add New Employee': 'បន្ថែមបុគ្គលិកថ្មី',
  'No employees found': 'រកមិនឃើញបុគ្គលិកទេ',
  'Pending Approvals': 'ការអនុម័តដែលកំពុងរង់ចាំ',
  'Branch Locations & Geofences': 'ទីតាំងសាខា និង Geofence',
  'Departments & Structure': 'ផ្នែក និងរចនាសម្ព័ន្ធ',
  'day': 'ថ្ងៃ',
  'days': 'ថ្ងៃ',
  'Invite New Employee': 'អញ្ជើញបុគ្គលិកថ្មី',
  'Add departments to organize teams within branches.': 'បន្ថែមផ្នែកដើម្បីរៀបចំក្រុមការងារនៅក្នុងសាខា។',
  'Attendance': 'វត្តមាន',
  'Overview': 'ទិដ្ឋភាពទូទៅ',
  'Department': 'នាយកដ្ឋាន',
  'Month': 'ខែ',
  'Year': 'ឆ្នាំ',
  'All months': 'គ្រប់ខែទាំងអស់',
  'All years': 'គ្រប់ឆ្នាំទាំងអស់',
  'Total Sessions': 'ចំនួនវេនសរុប',
  'Absent with Permission': 'អវត្តមានមានការអនុញ្ញាត',
  'Waive': 'លើកលែង',
  ' Session': ' វេន',
  ' Sessions': ' វេន',
  'Forgot password?': 'ភ្លេចពាក្យសម្ងាត់?',
  'Enter your email and we\'ll send you a link to reset your password.': 'បញ្ចូលអ៊ីមែលរបស់អ្នក ហើយយើងនឹងផ្ញើតំណភ្ជាប់ដើម្បីកំណត់ពាក្យសម្ងាត់ឡើងវិញ។',
  'Send reset link': 'ផ្ញើតំណកំណត់ឡើងវិញ',
  'Back to login': 'ត្រឡប់ទៅចូលគណនី',
  'FAST DEMO ACCESS': 'ការចូលសាកល្បងរហ័ស',
  'Role': 'តួនាទី',
  'Pass': 'លេខសម្ងាត់',
  'Admin': 'អ្នកគ្រប់គ្រងប្រព័ន្ធ',
};
