// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBImqg66hC5fppWlOhx5SfPkYs0STRHx8I',
    appId: '1:1039047136384:web:11daa17ed846c764f80265',
    messagingSenderId: '1039047136384',
    projectId: 'face-recognition-attenda-230d3',
    authDomain: 'face-recognition-attenda-230d3.firebaseapp.com',
    storageBucket: 'face-recognition-attenda-230d3.firebasestorage.app',
    measurementId: 'G-6M3JT5PD3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUKwnBoIIiRth_zPSICB_F21ZTda4Yeaw',
    appId: '1:1039047136384:android:2329b231cb7ea65df80265',
    messagingSenderId: '1039047136384',
    projectId: 'face-recognition-attenda-230d3',
    storageBucket: 'face-recognition-attenda-230d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa1tUW-BqNhYtVfRTccRjvE3-1N6zdrGs',
    appId: '1:1039047136384:ios:92124ddd9f27ebaff80265',
    messagingSenderId: '1039047136384',
    projectId: 'face-recognition-attenda-230d3',
    storageBucket: 'face-recognition-attenda-230d3.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognitionAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa1tUW-BqNhYtVfRTccRjvE3-1N6zdrGs',
    appId: '1:1039047136384:ios:92124ddd9f27ebaff80265',
    messagingSenderId: '1039047136384',
    projectId: 'face-recognition-attenda-230d3',
    storageBucket: 'face-recognition-attenda-230d3.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognitionAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBImqg66hC5fppWlOhx5SfPkYs0STRHx8I',
    appId: '1:1039047136384:web:65c6a72705774e0ff80265',
    messagingSenderId: '1039047136384',
    projectId: 'face-recognition-attenda-230d3',
    authDomain: 'face-recognition-attenda-230d3.firebaseapp.com',
    storageBucket: 'face-recognition-attenda-230d3.firebasestorage.app',
    measurementId: 'G-8FXH2RVXKJ',
  );
}
